spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # product
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # order
        - id: order_route
          uri: lb://gulimall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 第三方服务
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}
        # 鉴权中心
        - id: auth_route
          uri: lb://gulimall-auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        # 会员服务
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        # 优惠服务
        - id: coupon_route
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        # 库存服务
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        # 搜索服务
        - id: search_route
          uri: lb://gulimall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        # 秒杀服务
        - id: seckill_route
          uri: lb://gulimall-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        # 购物车服务
        - id: cart_route
          uri: lb://gulimall-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
